# Generated by Django 2.2.4 on 2019-08-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190820_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='id_post',
        ),
        migrations.AddField(
            model_name='posts',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
