# Generated by Django 2.2.4 on 2019-08-21 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190820_2351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
