# Generated by Django 2.2.4 on 2019-08-21 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
